// Code generated by "stringer -type=BrushMode -output mode_string.go -linecomment"; DO NOT EDIT.

package goralb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeOff-0]
	_ = x[ModeDailyClean-1]
	_ = x[ModeSensitive-2]
	_ = x[ModeMassage-3]
	_ = x[ModeWhitening-4]
	_ = x[ModeDeepClean-5]
	_ = x[ModeTongueCleaning-6]
	_ = x[ModeTurbo-7]
	_ = x[ModeUnknown-255]
}

const (
	_BrushMode_name_0 = "OffDailySensitiveMassageWhiteningDeep CleanTongue CleaningTurbo"
	_BrushMode_name_1 = "Unknown"
)

var (
	_BrushMode_index_0 = [...]uint8{0, 3, 8, 17, 24, 33, 43, 58, 63}
)

func (i BrushMode) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _BrushMode_name_0[_BrushMode_index_0[i]:_BrushMode_index_0[i+1]]
	case i == 255:
		return _BrushMode_name_1
	default:
		return "BrushMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
